spring.application.name=film-watchlist

server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# OMDB API kljuc
omdb.api.key=5c8bb177
omdb.api.url=https://www.omdbapi.com/

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
